### PR TITLE
something wrong when I choose Chinese as language

### PR DESCRIPTION
**Pull request by duxiuxing**
1. copy all .ttf files to apps/fceugx in workflow, I can choose language as Chinese now
2. I think LANG_DEFAULT = LANG_ENGLISH define is a good habit, so I can build a Chinese version in my fork branch easyly 
3. if run from channel forwarder, argv[0] would begin with sd1:/, so will lead to a failure of LoadFont()

from channel

### CODE REVIEW

**Comment by duxiuxing** [comment]
I clicked fceugx channel in Korea Wii, argc of main() would be 0, so I set a default value to appPath before CreateAppPath()

from channel in Korea Wii

**Comment by dborth** [comment]
Isn't the problem here that the forwarder is passing in sd1 instead of sd? Are all the other changes really required?

**Comment by saulfabregwiivc** [comment]
Also, can you share your forwarder channel you're using and the fonts?

**Comment by duxiuxing** [comment]
> Isn't the problem here that the forwarder is passing in sd1 instead of sd? Are all the other changes really required?

Case 1 : if arg[0] = sd:/apps/fceugx/boot.dol，CreateAppPath() would set appPath=sd:/apps/fceugx, this is a correct path, everything would be fine after CreateAppPath(). But In Case 2 : if arg[0] = sd1:/apps/fceugx/boot.dol, after CreateAppPath() ran, appPath still empty, appPath would be set sd:/fceugx in LoadPrefsFromMethod(). 

In LoadFont(), the path of *.ttf is combine by appPath, Case 2 would cause LoadFont() fail, and show a error prompt "Font file not found!". This is a bug！

Other changes are just a small suggestion. It is not for a bug fix.

**Comment by saulfabregwiivc** [comment]
> > Also, can you share your forwarder channel you're using and the fonts?
> 
> I build a Chinese version by the fork branch, you can find the fonts (*.ttf) files in the apps/fceugx folder. https://share.weiyun.com/C2o1A912

can't download from that link. Can you upload it here or in MediaFire?

**Comment by dborth** [comment]
I've taken the change to switch sd1:/ to sd:/ but I don't see sufficient justification to apply the remainder of the changes.

**Pull request closed without merging**
